import {
  TbHelpSquareRoundedFilled,
  TbSquareRounded,
  TbSquareRoundedFilled,
} from 'react-icons/tb';
import FilterOption from './FilterOption';

const SelectedColor = () => {
  return (
    <div className="flex flex-col gap-1 p-2">
      색상
      <div className="flex flex-row gap-1">
        <FilterOption
          label="분홍"
          icon={TbSquareRoundedFilled}
          field="selectedColor"
          value="분홍"
          color="pink"
        />
        <FilterOption
          label="빨강"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="빨강"
          color="red"
        />
        <FilterOption
          label="주황"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="주황"
          color="orange"
        />
        <FilterOption
          label="노랑"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="노랑"
          color="yellow"
        />
        <FilterOption
          label="연두"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="연두"
          color="lime"
        />
        <FilterOption
          label="초록"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="초록"
          color="green"
        />
        <FilterOption
          label="청록"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="청록"
          color="teal"
        />
        <FilterOption
          label="파랑"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="파랑"
          color="blue"
        />
      </div>
      <div className="flex flex-row gap-1">
        <FilterOption
          label="남색"
          icon={TbSquareRoundedFilled}
          field="selectedColor"
          value="남색"
          color="darkblue"
        />
        <FilterOption
          label="자주"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="자주"
          color="fuchsia"
        />
        <FilterOption
          label="보라"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="보라"
          color="indigo"
        />
        <FilterOption
          label="회색"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="회색"
          color="gray"
        />
        <FilterOption
          label="검정"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="검정"
          color="black"
        />
        <FilterOption
          label="하양"
          icon={TbSquareRoundedFilled}
          field={'selectedColor'}
          value="하양"
          color="white"
        />
        <FilterOption
          label="투명"
          icon={TbSquareRounded}
          field={'selectedColor'}
          value="투명"
          color="white"
        />
        <FilterOption
          label="전체"
          icon={TbHelpSquareRoundedFilled}
          field={'selectedColor'}
          value="전체"
          color="white"
        />
      </div>
    </div>
  );
};

export default SelectedColor;
